### ISSUE TITLE
Should this repo be sunset?

### ISSUE THREAD

**Issue by edmorley** [buildpacks/tekton-integration#40]
The last commit to this repo was 3 years ago, and PRs aren't being reviewed (eg #39) - as such it seems this repo is unmaintained? Should it be archived to make the current status clearer?

**Comment by jjbustamante** [comment]
I think the answer is yes! 
I have in my TODO list to open the conversation to archive this repository, thanks for creating this issue @edmorley

**Comment by edmorley** [comment]
Just checking in about the status of this?

If we're not yet ready to sunset the repo, could we at least merge the docs only #39?

**Comment by edmorley** [comment]
In #39 we found that CI is completely broken at the moment.

I think this is another reason we should archive this repo now. (It can always be unarchived in the future if this project is resurrected.)

**Comment by jjbustamante** [comment]
> In #39 we found that CI is completely broken at the moment.
> 
> I think this is another reason we should archive this repo now. (It can always be unarchived in the future if this project is resurrected.)

@hone @jkutner do we have a process in place to archive repo under CNB?

**Comment by jjbustamante** [comment]
My thoughts about this:

- If I am not wrong, this repository is just a **staging** area for any change that we want to make in the Tekton Catalog
  - [buildpack-phases](https://github.com/tektoncd/catalog/tree/main/task/buildpacks-phases)
  - [buildpack](https://github.com/tektoncd/catalog/tree/main/task/buildpacks) 
-  David and Javier were responsible in the past for keeping up to date with the API versions available in Tekton, honestly, I haven't tried to do this, as a Platform maintainer, I think, is part of my duties but I do not have the bandwidths right now.
-  We should update the OWNER files mentioned above, I can do that.
-  If we archive this repository, the only side effect will be we won't have a way to easily test an update to the catalog before merging it, right?

**Comment by edmorley** [comment]
This integration is currently buggy/broken btw, and people are using it not realising it's not actively maintained:
https://github.com/heroku/buildpacks-python/issues/196

**Comment by swarupdonepudi** [comment]
@edmorley since this buildpack is not working, what is the other alterantive to use buildpacks on tekton?

**Comment by edmorley** [comment]
@swarupdonepudi I'm sorry I have no idea - I've never used Tekton. 

(The only reason I opened this issue was that this repo references a builder image name that's outdated, and my PR to update that reference was never merged due to CI on `main` permafailing. Then later, I had someone open an issue against my CNB's repo, caused not by a bug in my buildpack, but this Tekton integration instead.)

**Comment by swarupdonepudi** [comment]
I see. thanks for the quick response @edmorley .

**Comment by cmoulliard** [comment]
> [@edmorley](https://github.com/edmorley) since this buildpack is not working, what is the other alterantive to use buildpacks on tekton?

Buildpacks is working using Tekton :-)

I updated the code of the task which is working with latest lifecycles releases and extension feature here: https://github.com/redhat-buildpacks/catalog/tree/main/tekton/task

There is also a testing project showing how to use it: https://github.com/redhat-buildpacks/testing?tab=readme-ov-file#3-tekton

**Comment by edmorley** [comment]
> Buildpacks is working using Tekton :-)

I may be misunderstanding (I've never used Tekton and have no knowledge of how this repo works), but it seems what you have is a working fork/alternative to this repo, which is great - but it still doesn't change the fact that this repo is broken with modern Buildpack APIs?

Either this repo needs to be fixed, or it needs to be sunset and users redirected to a maintained fork (like yours?).

**Comment by cmoulliard** [comment]
> Either this repo needs to be fixed, or it needs to be sunset and users redirected to a maintained fork (like yours?).

I'm in favor to sunset this repository as an official upstream hub of the buildpack tasks exist: https://hub.tekton.dev/tekton/task/buildpacks and is used as input documentation here https://buildpacks.io/docs/for-platform-operators/how-to/integrate-ci/tekton/

What I propose is to submit my changes to the upstream Tekton Hub and open a PR on buildpacks.io doc site too. 

**Remark**: There is an error within the [hub tekton page](https://hub.tekton.dev/tekton/task/buildpacks) as the git repository of the Tekton Task is: https://github.com/tektoncd/catalog/master/task/buildpacks

Help is more than welcome !

**Comment by cmoulliard** [comment]
Do you agree that we keep one Task within the Tekton/Catalog github repo `buildpack-phases` and not anymore `buildpack` Task ?

**Comment by cmoulliard** [comment]
The new Buildpacks phases - 0.3 (supporting spec 0.13) has been published on the Tekton Catalog : https://github.com/tektoncd/catalog/tree/main/task/buildpacks-phases/0.3 

FYI: @edmorley @jjbustamante @swarupdonepudi @jkutner

**Comment by edmorley** [comment]
@cmoulliard That's amazing, thank you!

It seems next steps might be to update the README of this repo to point to the new repos/project and indicate this repo is deprecated/sunset? (Perhaps also disabling CI, so the PR can be merged) After which we could archive this repo?

If so, would you have a spare moment to open a PR here to do this? :-)

**Comment by cmoulliard** [comment]
> It seems next steps might be to update the README of this repo to point to the new repos/project and indicate this repo is deprecated/sunset? (Perhaps also disabling CI, so the PR can be merged) After which we could archive this repo?
> 
> If so, would you have a spare moment to open a PR here to do this? :-)

Yes. This repo should be archived and owner(s) should add a remark top of the README.md
